image: node:6.10

stages:
    - install # install all npm dependencies
    - test    # execute unit tests
    - deploy # deploy to aws

npmInstallGlobals:
  stage: install
  script: 
    - npm install -g serverless
npmInstall:
    stage: install
    script:
        - npm install
    # artifacts describe the result of the stage
    # that can be used in consecutive stages
    artifacts:
        untracked: true

linting:
    stage: test
    script:
        # install standardjs for linting
        - npm install -g standard
        - npm run-script lint

deploytodevaws:
    stage: deploy
    # use the artifcats of the 'npmInstall' job
    dependencies:
        - npmInstallGlobals
        - npmInstall
    script:
        # install dev-dependency mocha
        - npm install
        - npm test
        - npm run deploy-dev
