image: node:latest

stages:
    - install # install all npm dependencies
    - test    # execute unit tests
    - deploy # deploy to aws

cache:
  paths:
    - node_modules/


npmInstallGlobals:
  stage: install
  script: 
    - npm install -g serverless
  artifacts:
      untracked: true
    
npmInstall:
    stage: install
    script:
        - npm install
    # artifacts describe the result of the stage
    # that can be used in consecutive stages
    artifacts:
      untracked: true

linting:
    stage: test
    script:
        # install standardjs for linting
        - npm run lintCheck

deploytodevaws:
    stage: deploy
    # use the artifcats of the 'npmInstall' job
    dependencies:
        - npmInstallGlobals
        - npmInstall
    script:
        # install dev-dependency mocha
        - npm install
        - npm run deploy-dev
