version: 2
jobs:
  build:
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: circleci/node:8.2
    steps:
      - checkout
      - run:
          name: Npm Install
          command: npm install
      - save_cache:
          key: dependency-cache-se-be-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:8.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-se-be-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm install tslint
      - run:
          name: Test
          command: npm run tslint
      - run:
          name: Build unit tests
          command: npm run compile-tests
      - run:
          name: Run unit tests and get code coverage
          command: npm run unit-tests
  deploy:
    working_directory: ~/serverlesseventsbe
    docker:
      - image: circleci/node:8.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-se-be-{{ checksum "package.json" }}
      - run:
          name: Npm Install
          command: npm install
      - run:
          name: Install global dependancies
          command: sudo npm install -g serverless
      - run:
          name: Create default profile on aws using credentials
          command: serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY
      - run:
          name: Deploy resources and upload code to aws
          command: npm run deploy-dev
          

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: AWS_CRED
          requires:
            - build