Resources:   
  EventsGqlElasticSearch:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      ElasticsearchVersion: "6.3"
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: false
        InstanceCount: "1"
        ZoneAwarenessEnabled: false
        InstanceType: "t2.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
        # Attention! Before you enable this lines, check out the README to avoid an open access policy
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "*"
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: "true"
