'use strict';

// tests for queryEvents
// Generated by serverless-jest-plugin

const mod = require('./../handler');

const jestPlugin = require('serverless-jest-plugin');
const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'queryEvents' });

describe('λ Function - queryEvents', () => {
  beforeAll((done) => {
//  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('Invoke / Initiate function test', () => {
    return wrapped.run({}).then((response) => {
      expect(response).not.toBe(null);
      expect(response).toHaveProperty('statusCode');
      expect(response).toHaveProperty('body');
      expect(response.statusCode).toBe(200);
    });
  });
});
